<?php
    $retoure = $this->loadRetoure($this->getId());
?>

<div class="pdfpage">
    <div class="header">
        <div class="logo">LOGO</div>
        <div class="cu-address">CUSTOMER</div>
        <div class="shop-address">PW ADDRESS</div>
        <div style="clear:both"></div>
    </div>
    <div class="order">TEST1234</div>
    <div class="footer"></div>
</div>

<div id="falz1"></div>
<div id="falz2"></div>